#ifndef QT_CALCULATOR_SEGMENTTYPE_H
#define QT_CALCULATOR_SEGMENTTYPE_H

enum SegmentType {
    CLOSING_BRACKET,
    OPENING_BRACKET,
    NUMBER,
    FUNCTION,
    CONSTANT,
    OPERATOR
};

#endif //QT_CALCULATOR_SEGMENTTYPE_H
